update

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -21,7 +21,12 @@ services:
     certbot:
         image: certbot/certbot:latest
         command: >
-            sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done"
+            sh -c "trap exit TERM; while :; do
+            certbot renew --webroot -w /var/www/certbot &&
+            echo 'Renewed. Reloading nginx...' &&
+            docker exec bots-nginx-1 nginx -s reload || echo 'Failed to reload nginx';
+            sleep 12h & wait $${!};
+            done"
         volumes:
             - ./certbot/www/:/var/www/certbot/:rw
             - ./certbot/conf/:/etc/letsencrypt/:rw
